### ISSUE TITLE
Change license?

### ISSUE THREAD

**Issue by TechnikEmpire** [m1lhaus/SimpleSqueezeNet#1]
I'd like to fork this and rewrite to use C++AMP but I'm wondering if you can relax the license.

**Comment by m1lhaus** [comment]
Hi, OK and what licence do you have in your mind?

**Comment by TechnikEmpire** [comment]
@m1lhaus Something that is commercial friendly? :D I publish a lot of open source stuff myself, but my interest in this project is commercial so the GPL3 just wouldn't work for me. Whatever you think, it is your work after all!

**Comment by m1lhaus** [comment]
Well you can use it for commercial purposes as you want, but my intention is that it will stay open source.

**Comment by TechnikEmpire** [comment]
Yeah I should have been clearer, my AMP rewrite would be open source. Its all good though no worries. I'll close out the issue. Thanks for your time!
